# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-28 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_bookinfo_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterModelOptions(
            name='peopleinfo',
            options={'verbose_name': '人物信息', 'verbose_name_plural': '人物信息'},
        ),
        migrations.AddField(
            model_name='peopleinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='book', verbose_name='图片'),
        ),
    ]
