# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-28 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190528_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleinfo',
            name='files',
            field=models.FileField(null=True, upload_to='files', verbose_name='文件'),
        ),
    ]
